### ISSUE TITLE
Java 8

### ISSUE THREAD

**Issue by autermann** [enviroCar/enviroCar-server#222]
Are there any objections to move to Java 8 or at least 7 for the server?

**Comment by matthesrieke** [comment]
nope. to my knowledge we are the only service providers :) @EHJ-52n: JDK 8 for the VM should not be an issue, right?

**Comment by EHJ-52n** [comment]
JDK 8 is not so easy but JDK 7 should be easy.

**Comment by matthesrieke** [comment]
not so easy but doable? quick google brought me to this: http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html

**Comment by autermann** [comment]
```shell
echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" >> /etc/apt/sources.list.d/java8.list
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" >> /etc/apt/sources.list.d/java8.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
apt-get update
apt-get install oracle-java8-installer
```

**Comment by autermann** [comment]
@matthesrieke damn... you were faster...

**Comment by EHJ-52n** [comment]
I might be able to install this during the weekly security updates tomorrow, but remember It'is Friday.

**Comment by EHJ-52n** [comment]
done.
