### ISSUE TITLE
Confirmation link sent during registering new user returns blank white page.

### ISSUE THREAD

**Issue by Mainakdey1** [enviroCar/enviroCar-server#499]
In the flutter app , while registering a new user , the confirmation link sent in the mail provided by the user when click returns a blank white page. This is very confusing for a new user since they can't be sure if the process worked or not. And since the flutter app requires one to be registered, this issue affects the whole app.
![ss](https://user-images.githubusercontent.com/81181897/141667541-10e3b21e-18ad-4747-b683-5fbf53d18bc2.jpg)
p.

This issue resides with the server but I haven't been able to locate the page that results in the blank page. Any help would be greatly appreciated.

**Comment by autermann** [comment]
Once confirmed, the user is redirected via an `303 See Other` to the [webapp](https://envirocar.org/app/#!/login). This is done [here](https://github.com/enviroCar/enviroCar-server/blob/dev/rest/src/main/java/org/envirocar/server/rest/resources/ConfirmResource.java#L56-L60).

I'm pretty sure the flutter app should not follow that link...

**Comment by Mainakdey1** [comment]
Thanks for the info! :-)
